/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ItemAssetIdRouteImport } from './routes/item/$assetId'
import { Route as UserUsernameRouteImport } from './routes/user/$username'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as UserUsernameIndexRouteImport } from './routes/user/$username.index'
import { Route as UserUsernameAccessoriesRouteImport } from './routes/user/$username.accessories'
import { Route as UserUsernameBodyRouteImport } from './routes/user/$username.body'
import { Route as UserUsernameClothingRouteImport } from './routes/user/$username.clothing'
import { Route as UserUsernameOutfitsRouteImport } from './routes/user/$username.outfits'
import { Route as UserUsernameOutfitOutfitIdRouteImport } from './routes/user/$username.outfit.$outfitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ItemAssetIdRoute = ItemAssetIdRouteImport.update({
  id: '/item/$assetId',
  path: '/item/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserUsernameIndexRoute = UserUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserUsernameRoute,
} as any)
const UserUsernameAccessoriesRoute = UserUsernameAccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => UserUsernameRoute,
} as any)
const UserUsernameBodyRoute = UserUsernameBodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => UserUsernameRoute,
} as any)
const UserUsernameClothingRoute = UserUsernameClothingRouteImport.update({
  id: '/clothing',
  path: '/clothing',
  getParentRoute: () => UserUsernameRoute,
} as any)
const UserUsernameOutfitsRoute = UserUsernameOutfitsRouteImport.update({
  id: '/outfits',
  path: '/outfits',
  getParentRoute: () => UserUsernameRoute,
} as any)
const UserUsernameOutfitOutfitIdRoute =
  UserUsernameOutfitOutfitIdRouteImport.update({
    id: '/outfit/$outfitId',
    path: '/outfit/$outfitId',
    getParentRoute: () => UserUsernameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/item/$assetId': typeof ItemAssetIdRoute
  '/user/$username': typeof UserUsernameRouteWithChildren
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/user/$username/accessories': typeof UserUsernameAccessoriesRoute
  '/user/$username/body': typeof UserUsernameBodyRoute
  '/user/$username/clothing': typeof UserUsernameClothingRoute
  '/user/$username/outfits': typeof UserUsernameOutfitsRoute
  '/user/$username/': typeof UserUsernameIndexRoute
  '/user/$username/outfit/$outfitId': typeof UserUsernameOutfitOutfitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/item/$assetId': typeof ItemAssetIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/user/$username/accessories': typeof UserUsernameAccessoriesRoute
  '/user/$username/body': typeof UserUsernameBodyRoute
  '/user/$username/clothing': typeof UserUsernameClothingRoute
  '/user/$username/outfits': typeof UserUsernameOutfitsRoute
  '/user/$username': typeof UserUsernameIndexRoute
  '/user/$username/outfit/$outfitId': typeof UserUsernameOutfitOutfitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/item/$assetId': typeof ItemAssetIdRoute
  '/user/$username': typeof UserUsernameRouteWithChildren
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/user/$username/accessories': typeof UserUsernameAccessoriesRoute
  '/user/$username/body': typeof UserUsernameBodyRoute
  '/user/$username/clothing': typeof UserUsernameClothingRoute
  '/user/$username/outfits': typeof UserUsernameOutfitsRoute
  '/user/$username/': typeof UserUsernameIndexRoute
  '/user/$username/outfit/$outfitId': typeof UserUsernameOutfitOutfitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/item/$assetId'
    | '/user/$username'
    | '/.mcp/invoke-tool/$tool'
    | '/user/$username/accessories'
    | '/user/$username/body'
    | '/user/$username/clothing'
    | '/user/$username/outfits'
    | '/user/$username/'
    | '/user/$username/outfit/$outfitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/item/$assetId'
    | '/.mcp/invoke-tool/$tool'
    | '/user/$username/accessories'
    | '/user/$username/body'
    | '/user/$username/clothing'
    | '/user/$username/outfits'
    | '/user/$username'
    | '/user/$username/outfit/$outfitId'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/item/$assetId'
    | '/user/$username'
    | '/.mcp/invoke-tool/$tool'
    | '/user/$username/accessories'
    | '/user/$username/body'
    | '/user/$username/clothing'
    | '/user/$username/outfits'
    | '/user/$username/'
    | '/user/$username/outfit/$outfitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ItemAssetIdRoute: typeof ItemAssetIdRoute
  UserUsernameRoute: typeof UserUsernameRouteWithChildren
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$assetId': {
      id: '/item/$assetId'
      path: '/item/$assetId'
      fullPath: '/item/$assetId'
      preLoaderRoute: typeof ItemAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username/': {
      id: '/user/$username/'
      path: '/'
      fullPath: '/user/$username/'
      preLoaderRoute: typeof UserUsernameIndexRouteImport
      parentRoute: typeof UserUsernameRoute
    }
    '/user/$username/accessories': {
      id: '/user/$username/accessories'
      path: '/accessories'
      fullPath: '/user/$username/accessories'
      preLoaderRoute: typeof UserUsernameAccessoriesRouteImport
      parentRoute: typeof UserUsernameRoute
    }
    '/user/$username/body': {
      id: '/user/$username/body'
      path: '/body'
      fullPath: '/user/$username/body'
      preLoaderRoute: typeof UserUsernameBodyRouteImport
      parentRoute: typeof UserUsernameRoute
    }
    '/user/$username/clothing': {
      id: '/user/$username/clothing'
      path: '/clothing'
      fullPath: '/user/$username/clothing'
      preLoaderRoute: typeof UserUsernameClothingRouteImport
      parentRoute: typeof UserUsernameRoute
    }
    '/user/$username/outfits': {
      id: '/user/$username/outfits'
      path: '/outfits'
      fullPath: '/user/$username/outfits'
      preLoaderRoute: typeof UserUsernameOutfitsRouteImport
      parentRoute: typeof UserUsernameRoute
    }
    '/user/$username/outfit/$outfitId': {
      id: '/user/$username/outfit/$outfitId'
      path: '/outfit/$outfitId'
      fullPath: '/user/$username/outfit/$outfitId'
      preLoaderRoute: typeof UserUsernameOutfitOutfitIdRouteImport
      parentRoute: typeof UserUsernameRoute
    }
  }
}

interface UserUsernameRouteChildren {
  UserUsernameAccessoriesRoute: typeof UserUsernameAccessoriesRoute
  UserUsernameBodyRoute: typeof UserUsernameBodyRoute
  UserUsernameClothingRoute: typeof UserUsernameClothingRoute
  UserUsernameOutfitsRoute: typeof UserUsernameOutfitsRoute
  UserUsernameIndexRoute: typeof UserUsernameIndexRoute
  UserUsernameOutfitOutfitIdRoute: typeof UserUsernameOutfitOutfitIdRoute
}

const UserUsernameRouteChildren: UserUsernameRouteChildren = {
  UserUsernameAccessoriesRoute: UserUsernameAccessoriesRoute,
  UserUsernameBodyRoute: UserUsernameBodyRoute,
  UserUsernameClothingRoute: UserUsernameClothingRoute,
  UserUsernameOutfitsRoute: UserUsernameOutfitsRoute,
  UserUsernameIndexRoute: UserUsernameIndexRoute,
  UserUsernameOutfitOutfitIdRoute: UserUsernameOutfitOutfitIdRoute,
}

const UserUsernameRouteWithChildren = UserUsernameRoute._addFileChildren(
  UserUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ItemAssetIdRoute: ItemAssetIdRoute,
  UserUsernameRoute: UserUsernameRouteWithChildren,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
